# 1.Torch中与tensor有关的最常用属性和函数有哪些？
![](./images/torch_tensor创建.jpg)<br>
![](./images/torch_tensor属性.jpg)<br>
![](./images/torch_tensor索引和切片.jpg)<br>
![](./images/torch_tensor数据类型转换.jpg)<br>
![](./images/torch_tensor数据shape操作.jpg)<br>
![](./images/torch_tensor算数计算.jpg)<br>
![](./images/torch_tensorGPU和自动求导.jpg)<br>

In [1]:
import torch
import numpy as np

In [13]:
'''Initializing  a Tensor'''
# 1.Directly from data
data = [
        [1, 2],
        [3, 4]
]

x_data = torch.tensor(data)

print(x_data)
print(type(x_data))
print(x_data.dtype)

tensor([[1, 2],
        [3, 4]])
<class 'torch.Tensor'>
torch.int64


In [12]:
# 2. From a Numpy array
np_array = np.array(data)
print(np_array)
print(type(np_array))

x_np = torch.from_numpy(np_array)
print(x_np)
print(type(x_np))
print(x_np.dtype)

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
<class 'torch.Tensor'>
torch.int32


# 1.初始化之后的tensor的dtype是由什么决定的？
这个问题来源于上述代码的输出中，第一个输出的tensor没有带dtype,而第二个输出中带了。
原因：<br>
在Pytorch的Tensor中，默认的数据类型是:<br>
&nbsp;&nbsp;&nbsp;&nbsp;(1)对于int类型：torch.int64<br>
&nbsp;&nbsp;&nbsp;&nbsp;(2)对于float类型，torch.float32<br>

&nbsp;&nbsp;&nbsp;&nbsp;而在第一个例子中，是直接从数据生成的tensor，那么数据的类型也由tensor自动推断，默认就是torch.int64类型，而默认类型，在输出tensor时，是不显示的；<br>
&nbsp;&nbsp;&nbsp;&nbsp;第二个例子中，因为是先从numpy.ndarray生成的，而ndarray对于int类型的默认dtype是np.int32，因此在生成tensor时，会自动推断为torch.int32，导致不是tensor的默认数据类型，因此会显示地输出。<br>

# 2.如何转换tensor和numpy的dtype？
![tensor和ndarray的dtype转换方法](./images/tensor和ndarray的dtype转换方法.jpg)

In [ ]:
# 3.From another tensor
# 新建的tensor会保留原有的属性（shape和datatype），除非显示地重写 
x_ones = torch.ones_like(x_data)
print(x_ones)

x_rand = torch.rand_like(x_data, dtype = torch.float) #override the datatype
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.1039, 0.2464],
        [0.9373, 0.6347]])


In [ ]:
#  4.With random or constant values
# Shpe is a tuple of tensor dimensions
shape = (2,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(rand_tensor)
print(ones_tensor)
print(zeros_tensor)

tensor([[0.6092, 0.1209, 0.3179],
        [0.3937, 0.3992, 0.8875]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
'''Attrbutes of a Tensor'''
tensor = torch.rand(3, 4)
print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

# 移动tensor的操作，都会返回新的移动之后的tensor，而不会改变原有的tensor，这是pytorch的
# 内部设置,是为了避免accidental overwriting, ensuring explicit control over where computations happen.
tensor_gpu = tensor.to("cuda") 
tensor_gpu_1 = tensor.cuda()
print(tensor_gpu.device)
print(tensor_gpu_1.device)

torch.Size([3, 4])
torch.float32
cpu
cuda:0
cuda:0


In [37]:
# 用于判断Cuda是否可用，以及GPU的设置 
print(torch.cuda.is_available())  # True if a GPU is available
print(torch.cuda.device_count())  # Number of GPUs available
print(torch.cuda.get_device_name(0))  # Name of the first GPU

True
1
NVIDIA GeForce RTX 4060 Laptop GPU


In [ ]:
'''Operations on Tensors'''
if torch.accelerator.is_available():
    tensor = tensor.to(torch.accelerator.current_accelerator())

In [ ]:
# 1.Standard numpy-like indexing and slicing:
tensor = torch.ones(4, 4)
print(tensor[0])
print(tensor[:, 1])

print(tensor[:, -1])
print(tensor[..., -1])

tensor[:, 1] = 0
print(tensor)

tensor_3d = torch.rand(3, 4, 4)
print(tensor_3d)
print(tensor_3d[..., -1])  # Selects the last column from each 2D slice

# Note:
# "..." 指的是slice 前面所有的维度；
# 当是2维数组时，tensor[:, -1]等价于tensor[..., -1]
# 如果是3维数组，tensor[..., -1]等价于tensor[:, :, -1]
# 如果是n维数组，tensor[..., -1]等价于tensor[:, :, 重复,:, -1]

tensor([1., 1., 1., 1.])
tensor([1., 1., 1., 1.])
tensor([1., 1., 1., 1.])
tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[[0.5909, 0.2303, 0.0955, 0.9692],
         [0.7367, 0.7870, 0.3499, 0.6610],
         [0.6881, 0.5135, 0.5637, 0.6185],
         [0.0351, 0.0614, 0.6553, 0.3489]],

        [[0.5170, 0.7386, 0.5188, 0.9104],
         [0.3352, 0.6535, 0.8963, 0.9468],
         [0.6955, 0.2645, 0.5405, 0.0114],
         [0.9743, 0.0647, 0.3262, 0.5512]],

        [[0.5151, 0.0262, 0.4394, 0.6635],
         [0.8396, 0.2170, 0.9283, 0.8664],
         [0.5285, 0.9629, 0.5405, 0.8921],
         [0.7249, 0.0570, 0.9306, 0.0887]]])
tensor([[0.9692, 0.6610, 0.6185, 0.3489],
        [0.9104, 0.9468, 0.0114, 0.5512],
        [0.6635, 0.8664, 0.8921, 0.0887]])


In [42]:
# Joining tensors
t1 = torch.cat([tensor, tensor, tensor], dim = 1)
print(t1)


tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


https://blog.csdn.net/weixin_39504171/article/details/106074550
https://blog.csdn.net/qq_40507857/article/details/119854085