# 1.Torch中与tensor有关的最常用属性和函数有哪些？
![](./images/torch_tensor创建.jpg)<br>
![](./images/torch_tensor属性.jpg)<br>
![](./images/torch_tensor索引和切片.jpg)<br>
![](./images/torch_tensor数据类型转换.jpg)<br>
![](./images/torch_tensor数据shape操作.jpg)<br>
![](./images/torch_tensor算数计算.jpg)<br>
![](./images/torch_tensorGPU和自动求导.jpg)<br>

In [2]:
import torch
import numpy as np

In [13]:
'''Initializing  a Tensor'''
# 1.Directly from data
data = [
        [1, 2],
        [3, 4]
]

x_data = torch.tensor(data)

print(x_data)
print(type(x_data))
print(x_data.dtype)

tensor([[1, 2],
        [3, 4]])
<class 'torch.Tensor'>
torch.int64


In [12]:
# 2. From a Numpy array
np_array = np.array(data)
print(np_array)
print(type(np_array))

x_np = torch.from_numpy(np_array)
print(x_np)
print(type(x_np))
print(x_np.dtype)

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
<class 'torch.Tensor'>
torch.int32


# 1.初始化之后的tensor的dtype是由什么决定的？
这个问题来源于上述代码的输出中，第一个输出的tensor没有带dtype,而第二个输出中带了。
原因：<br>
在Pytorch的Tensor中，默认的数据类型是:<br>
&nbsp;&nbsp;&nbsp;&nbsp;(1)对于int类型：torch.int64<br>
&nbsp;&nbsp;&nbsp;&nbsp;(2)对于float类型，torch.float32<br>

&nbsp;&nbsp;&nbsp;&nbsp;而在第一个例子中，是直接从数据生成的tensor，那么数据的类型也由tensor自动推断，默认就是torch.int64类型，而默认类型，在输出tensor时，是不显示的；<br>
&nbsp;&nbsp;&nbsp;&nbsp;第二个例子中，因为是先从numpy.ndarray生成的，而ndarray对于int类型的默认dtype是np.int32，因此在生成tensor时，会自动推断为torch.int32，导致不是tensor的默认数据类型，因此会显示地输出。<br>

# 2.如何转换tensor和numpy的dtype？
![tensor和ndarray的dtype转换方法](./images/tensor和ndarray的dtype转换方法.jpg)

In [ ]:
# 3.From another tensor
# 新建的tensor会保留原有的属性（shape和datatype），除非显示地重写 
x_ones = torch.ones_like(x_data)
print(x_ones)

x_rand = torch.rand_like(x_data, dtype = torch.float) #override the datatype
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.1039, 0.2464],
        [0.9373, 0.6347]])


In [ ]:
#  4.With random or constant values
# Shpe is a tuple of tensor dimensions
shape = (2,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(rand_tensor)
print(ones_tensor)
print(zeros_tensor)

tensor([[0.6092, 0.1209, 0.3179],
        [0.3937, 0.3992, 0.8875]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
'''Attrbutes of a Tensor'''
tensor = torch.rand(3, 4)
print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

# 移动tensor的操作，都会返回新的移动之后的tensor，而不会改变原有的tensor，这是pytorch的
# 内部设置,是为了避免accidental overwriting, ensuring explicit control over where computations happen.
tensor_gpu = tensor.to("cuda") 
tensor_gpu_1 = tensor.cuda()
print(tensor_gpu.device)
print(tensor_gpu_1.device)

torch.Size([3, 4])
torch.float32
cpu
cuda:0
cuda:0


In [37]:
# 用于判断Cuda是否可用，以及GPU的设置 
print(torch.cuda.is_available())  # True if a GPU is available
print(torch.cuda.device_count())  # Number of GPUs available
print(torch.cuda.get_device_name(0))  # Name of the first GPU

True
1
NVIDIA GeForce RTX 4060 Laptop GPU


In [ ]:
'''Operations on Tensors'''
if torch.accelerator.is_available():
    tensor = tensor.to(torch.accelerator.current_accelerator())

In [ ]:
# 1.Standard numpy-like indexing and slicing:
tensor = torch.ones(4, 4)
print(tensor[0])
print(tensor[:, 1])

print(tensor[:, -1])
print(tensor[..., -1])

tensor[:, 1] = 0
print(tensor)

tensor_3d = torch.rand(3, 4, 4)
print(tensor_3d)
print(tensor_3d[..., -1])  # Selects the last column from each 2D slice

# Note:
# "..." 指的是slice 前面所有的维度；
# 当是2维数组时，tensor[:, -1]等价于tensor[..., -1]
# 如果是3维数组，tensor[..., -1]等价于tensor[:, :, -1]
# 如果是n维数组，tensor[..., -1]等价于tensor[:, :, 重复,:, -1]

tensor([1., 1., 1., 1.])
tensor([1., 1., 1., 1.])
tensor([1., 1., 1., 1.])
tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[[0.5909, 0.2303, 0.0955, 0.9692],
         [0.7367, 0.7870, 0.3499, 0.6610],
         [0.6881, 0.5135, 0.5637, 0.6185],
         [0.0351, 0.0614, 0.6553, 0.3489]],

        [[0.5170, 0.7386, 0.5188, 0.9104],
         [0.3352, 0.6535, 0.8963, 0.9468],
         [0.6955, 0.2645, 0.5405, 0.0114],
         [0.9743, 0.0647, 0.3262, 0.5512]],

        [[0.5151, 0.0262, 0.4394, 0.6635],
         [0.8396, 0.2170, 0.9283, 0.8664],
         [0.5285, 0.9629, 0.5405, 0.8921],
         [0.7249, 0.0570, 0.9306, 0.0887]]])
tensor([[0.9692, 0.6610, 0.6185, 0.3489],
        [0.9104, 0.9468, 0.0114, 0.5512],
        [0.6635, 0.8664, 0.8921, 0.0887]])


In [ ]:
# 2.Joining tensors
t1 = torch.cat([tensor, tensor, tensor], dim = 1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [4]:
# 假设是时间步T1的输出
T1 = torch.tensor([[1, 2, 3],
        		[4, 5, 6],
        		[7, 8, 9]])
# 假设是时间步T2的输出
T2 = torch.tensor([[10, 20, 30],
        		[40, 50, 60],
        		[70, 80, 90]])

print(torch.stack((T1, T2)))
print(torch.stack((T1, T2), dim = 1))
print(torch.stack((T1, T2), dim = 2))
print(torch.stack((T1, T2), dim = 3))


tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 20, 30],
         [40, 50, 60],
         [70, 80, 90]]])
tensor([[[ 1,  2,  3],
         [10, 20, 30]],

        [[ 4,  5,  6],
         [40, 50, 60]],

        [[ 7,  8,  9],
         [70, 80, 90]]])
tensor([[[ 1, 10],
         [ 2, 20],
         [ 3, 30]],

        [[ 4, 40],
         [ 5, 50],
         [ 6, 60]],

        [[ 7, 70],
         [ 8, 80],
         [ 9, 90]]])


IndexError: Dimension out of range (expected to be in range of [-3, 2], but got 3)

# 1.torch.stack()和torch.cat()的区别
## 1.1 参考的博客链接
https://blog.csdn.net/weixin_39504171/article/details/106074550
https://blog.csdn.net/qq_40507857/article/details/119854085

## 1.2 具体的理解-stack
&nbsp;&nbsp;&nbsp;&nbsp;（1）torch.stack的官方文档链接：https://pytorch.org/docs/stable/generated/torch.stack.html<br>
stack是在一个新的dim维度，将待处理的tensor序列拼接在一起，dim的范围在0和拼接后tensor的维度数量之间；这里的维度数量指的是拼接后张量的维度个数，因为stack函数会提升张量的维度，比如二维张量stack会变成三维，三维张量stack会变为四维，n维张量stack会变为n+1维，因此对应的，拼接的时候dim的范围分别是[0,2], [0,3], [0,n-1]。<br>
&nbsp;&nbsp;&nbsp;&nbsp;（2）更简单的理解，对于待拼接的k个tensor，他们的shape必须是一样的，比如都是(m, n)。那么在stack的时候，dim的范围在[0, 2]之间，-1代表最后一维，不显示指定，默认是0维；<br>
拼接之后的tensor会变成三维的，并且在dim的索引位置插入一个新的维度，索引的上限为待拼接的tensor的个数，也就是k-1。根据这0个例子，假设dim = 0, 那么拼接之后的tensor的shape为(k, m, n), 并且concatenated_tensor[k][i][j] = 待拼接的第 k + 1 个tensor的[i][j]（这里k和k+1是因为索引和实际的顺序是差1的）；假设dim = 1, 那么拼接之后的tensor的shape为(m, k, n); 假设dim = 1, 那么拼接之后的tensor的shape为(m, n, k) <br>
&nbsp;&nbsp;&nbsp;&nbsp;（3）stack一般用于将多个相同形状的张量组合成一个更高维度的张量，例如将多个时间步的特征向量堆叠成一个序列张量，同时也可以用于将多个数据sample整合到一个batch中。<br>
!注意!：上述的文字过程，实际上就是博客中的文字理解，建议搭配起来看，更容易理解。

## 1.3 具体的理解-cat
&nbsp;&nbsp;&nbsp;&nbsp;cat的待拼接tensor的shape也是要求一致的，但是dim是在已有的某个维度上拼接，而不会产生新的维度，比如待拼接的tensor都是二维的(m, n)，那么dim的范围是[0, 1]，表示只能在已有的维度上进行合并。

In [45]:
# 3.Arithmetic operations
# 3.1 matrix multiplication
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out = y3)

print(tensor)
print(y1)
print(y2)
print(y3)

# Note:
# 1.tensor的矩阵想乘是用 @
# 2.矩阵的转置使用 .T

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


In [48]:
# 3.2 element-wise product
z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out = z3)

print(tensor)
print(z1)
print(z2)
print(z3)

# Note:
# tensor的element-wise相乘，使用的是 * 

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [51]:
# 4.Single-element tensor
# 对于只有一个元素的tensor,可以使用 .item()函数，将tensor的数值转换为Python的数值类型
agg = tensor.sum()
print(agg)

agg_item = agg.item()
print(agg_item)
print(type(agg_item))

tensor(12.)
12.0
<class 'float'>


In [52]:
# 5.In-place operations
# 会将操作的计算结果存储回操作数的操作,叫 in-place的操作。通常使用 _下标来表示，但是这样的操作并不鼓励使用。
# 因为虽然这样的操作能够节省内存，但是在计算导数的时候容易出现问题。
print(tensor)
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [56]:
'''Bridge with Numpy'''
# 在CPU上的Tensor和Numpy的arrays能够共享内存的位置，并且改变其中一个，另外一个也会改变。
# 1.Tensor --> Numpy Array
t = torch.ones(5)
print(t)
print(t.dtype)

n = t.numpy()
print(n)
print(n.dtype)

tensor([1., 1., 1., 1., 1.])
torch.float32
[1. 1. 1. 1. 1.]
float32


In [57]:
t.add_(1)

print(t)
print(n)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [59]:
# 2.Numpy --> Tensor
n = np.ones(5)
t = torch.from_numpy(n)
print(n)
print(n.dtype)
print(t)

[1. 1. 1. 1. 1.]
float64
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [ ]:
np.add(n, 1, out = n)

print(n)
print(t)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


Tensor -》 Numpy： 使用.numpy()函数；反过来使用torch.from_numpy()函数；<br>
注意两种方法最后的返回都是一个新的变量，需要用新的变量来承接，也就是说不是in-place的操作。